### ISSUE TITLE
Pool mining support

### ISSUE THREAD

**Issue by c3msu** [KlausT/Sia-CUDA-Miner#5]
Hi,

There're some pool for Sia mining in beta testing now. You can see http://sia.nanopool.org. Can you try to add pool support for CUDA miner? That will be great. Gominer with nvidia GPU will suffer a very high CPU usage. 

Thanks.

**Comment by KlausT** [comment]
I think this could take a while, depending on if it is a bad hack, or proper support.

**Comment by c3msu** [comment]
thanks. I think it's proper support as Claymore's dual miner also support nano pool.  https://bitcointalk.org/index.php?topic=1433925.0

**Comment by c3msu** [comment]
This is from Claymore's miner setting: seems it can be used in network.cpp?

For SIA - nanopool, mandatory to use URL -dpool http://sia-eu1.nanopool.org:9980/miner/header?address=your_sia_wallet

**Comment by iRybin** [comment]
Yes - pool support is a musthave at the moment - gominer gives only 580 on GTX 970
