### ISSUE TITLE
Client hashing speed significantly slower than pool reports.

### ISSUE THREAD

**Issue by xurious** [KlausT/Sia-CUDA-Miner#6]
Client was showing hashrate of 314MH/s, 477 shares submitted (over the course of about an hour.) Pool reported 37MH/s.

Not sure how to generate a detail log to see exactly what is happening.

**Comment by KlausT** [comment]
Yeah, I have an idea what's causing this.
The miner is only submitting one solution per kernel call.
When we have low difficulties then more than one can be found per kernel call.

**Comment by KlausT** [comment]
Version 4.01 is a little better, but there is a lot of overhead at low difficulties.
As soon as I have figured out how to do multithreading this will probably be better.
