### ISSUE TITLE
Add Worker Name/ID as a parameter

### ISSUE THREAD

**Issue by dephcon** [KlausT/Sia-CUDA-Miner#7]
Started siamining.com pool today and quickly switched to your client as it's much better on Windows.  Just wondering if you're able to add support to pass through the worker name that they use on their gominer client:

./gominer -H siamining.com:9980 -Q "address=YourSiacoinAddress&worker=YourWorkerName"

**Comment by KlausT** [comment]
right now you could use this:
-q "youraddress&worker=something"

**Comment by dephcon** [comment]
thanks man!
